### ISSUE TITLE
Fix errors that happened during testing the tool

### ISSUE THREAD

**Issue by YasserKhalilExcelEgy** [yilmazdegirmenci/ExeIntoExcel#1]
Hello
I have tried to test the tool but I encountered errors .. and I have no background at python

Traceback (most recent call last):
  File "ExeIntoExcel.py", line 112, in <module>
    main(sys.argv[1:])
  File "ExeIntoExcel.py", line 27, in main
    dumpFile(filename)
  File "ExeIntoExcel.py", line 107, in dumpFile
    FILE.write(bytes.encode('hex'))
AttributeError: 'bytes' object has no attribute 'encode'

Any help how to fix the errors ..?

**Comment by hakanonymos** [comment]
it is writen with python 2.7

**Comment by hakanonymos** [comment]
this tool working but need to remove some thing , i have tested with office 2016 and excel and working after make some modification . it is writen with python 2.7
